### ISSUE TITLE
Folded heading text not shown 

### ISSUE THREAD

**Issue by ttrei** [matcatc/vim-asciidoc-folding#3]
Given a sample document
```
= Title

== Section 1

aaa

=== Sub-section 1.1

bbb

=== Sub-section 1.2

ccc

== Section 2

ddd
```

In vim 8.2 heading text is missing from folds
```
= Title

+-- 12 lines folded ---------------------------------------------------------------------------------------------------
+--  3 lines folded ---------------------------------------------------------------------------------------------------
```

In neovim 0.4.4 it looks better
```
= Title

== [64.7%] Section 1 [11/17 lines]·····················································································
== [11.8%] Section 2 [2/17 lines]······················································································
```

Didn't test on older versions of vim.

**Comment by ttrei** [comment]
There is a similar issue in vim-markdown-folding:
https://github.com/masukomi/vim-markdown-folding/issues/42

And a pull-request that fixes it, supposedly in backwards-compatible manner:
https://github.com/masukomi/vim-markdown-folding/pull/43

I tried those changes and now vim 8.2 behaves similarly to neovim 0.4.4:
```
= Title

== [64.7%] Section 1 [11/17 lines]-------------------------------------------------------------------------------------
== [11.8%] Section 2 [2/17 lines]--------------------------------------------------------------------------------------
```

**Comment by matcatc** [comment]
Thanks for bringing this to my attention. I quickly tested the fix and confirmed your results. I'll try to get the fix uploaded soon.

**Comment by matcatc** [comment]
Closing issue as fixed. Please re-open if I missed anything.
